# Generated by Django 5.2 on 2025-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0002_remove_doctor_user_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Dr. Unknown', max_length=100),
        ),
    ]
