# Generated by Django 5.2 on 2025-04-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0003_alter_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('pending', 'Pending Approval')], max_length=20),
        ),
    ]
