# Generated by Django 5.2 on 2025-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0007_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.AddField(
            model_name='pet',
            name='is_pet_owner',
            field=models.BooleanField(default=False),
        ),
    ]
