# Generated by Django 5.2 on 2025-04-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0008_remove_pet_owner_pet_is_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_pet_owner',
        ),
    ]
