# Generated by Django 5.2 on 2026-02-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0012_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('pending', 'Pending Approval')], default='available', max_length=20),
        ),
    ]
