# Generated by Django 5.2 on 2026-02-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0014_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
